# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chat_service_pb2 as chat__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Chat service for RAG operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessChat = channel.unary_unary(
                '/sage_rag.ChatService/ProcessChat',
                request_serializer=chat__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/sage_rag.ChatService/SearchDocuments',
                request_serializer=chat__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=chat__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/sage_rag.ChatService/GetHealth',
                request_serializer=chat__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=chat__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/sage_rag.ChatService/GetStats',
                request_serializer=chat__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=chat__service__pb2.StatsResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Chat service for RAG operations
    """

    def ProcessChat(self, request, context):
        """Process a chat message and return an AI-generated response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Search for documents in the knowledge base
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Get health status of the RAG service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get service statistics (admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessChat': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessChat,
                    request_deserializer=chat__service__pb2.ChatRequest.FromString,
                    response_serializer=chat__service__pb2.ChatResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=chat__service__pb2.SearchRequest.FromString,
                    response_serializer=chat__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=chat__service__pb2.HealthRequest.FromString,
                    response_serializer=chat__service__pb2.HealthResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=chat__service__pb2.StatsRequest.FromString,
                    response_serializer=chat__service__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sage_rag.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sage_rag.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat service for RAG operations
    """

    @staticmethod
    def ProcessChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sage_rag.ChatService/ProcessChat',
            chat__service__pb2.ChatRequest.SerializeToString,
            chat__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sage_rag.ChatService/SearchDocuments',
            chat__service__pb2.SearchRequest.SerializeToString,
            chat__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sage_rag.ChatService/GetHealth',
            chat__service__pb2.HealthRequest.SerializeToString,
            chat__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sage_rag.ChatService/GetStats',
            chat__service__pb2.StatsRequest.SerializeToString,
            chat__service__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
